// import { Injectable } from '@angular/core';

// @Injectable({
//   providedIn: 'root'   //generated by cli
// }) 
export class LoggingService{
    logStatusChange(status: string){
        console.log('A server status changed, new status: ' + status);
    }
}